
server:
  port: 8088

xdrpc:
  providers: http://localhost:8081/, http://localhost:8082, http://localhost:8083
  zkService: localhost:2181
  zkRoot: xdrpc

app:
  id: app1
  namespace: public
  env: dev
  version: v1.0